---
name: Lint

on: push

jobs:
  yaml_lint:
    name: YAML Lint
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ibiqlik/action-yamllint@v3.0.0
        with:
          config_file: .yamllint.yml
          strict: false
  markdown_lint:
    name: Markdown Lint
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
